export const personalityTypes = [
  "Brave",
  "Logical",
  "Hot-headed",
  "Kind",
  "Mysterious",
  "Sarcastic",
  "Optimistic",
  "Cunning",
  "Shy",
  "Cold & Emotionless",
  "Wise",
  "Rebellious",
  "Humble",
  "Prideful",
  "Charismatic",
] as const;

export const speechStyles = [
  "Formal",
  "Casual",
  "Slang-heavy",
  "Poetic",
  "Soft-spoken",
  "Fast-talking",
  "Monotone",
  "Eloquent",
  "Blunt",
  "Sarcastic",
  "Quiet & Reserved",
] as const;

export const coreMotivations = [
  "Revenge",
  "Love",
  "Justice",
  "Survival",
  "Knowledge",
  "Power",
  "Freedom",
  "Greed",
  "Loyalty",
  "Exploration",
  "Redemption",
  "Duty",
  "Fame",
  "Curiosity",
  "Family",
  "Self-Discovery",
  "Peace",
  "Thrill-Seeking",
  "Friendship",
  "Adventure",
] as const;
